#ifndef BURGERS_H_
#define BURGERS_H_

// Imports
#include <json/json.h>

// Self-Imports

// Headers
void runBurgers(Json::Value dBurg);

// ONCE I RUN DNS AND LES I WILL HAVE A BETTER IDEA ON HOW I WANT TO ORGANIZE THIS FILES AND INTEGRATE IT TO THE MAIN STRUCTURE
// FOR NOW THE NEW JSON WILL BE READ BY THE SAME MAIN AND IF BURGERS JUST GO DIRECTLY TO THIS SOLVER ELSE GO TO THE REGULAR ONE
// WHEN FINISHED REWRITE JSON AS WELL TO ORGANIZE INFORMATION IN A BETTER WAY

#endif
